### ISSUE TITLE
Multiple errors in following `low-quality-cells.Rmd` vignette

### ISSUE THREAD

**Issue by k3yavi** [hms-dbmi/dropEst#65]
Hi guys,
I was wondering has anybody else faced the following issues while using `low-quality-cells.Rmd` vignette to filter out low quality cells ? 

L37 & L38:
```
Error in ScorePipelineCells(pipeline_data, filter.high.mit.fraction = T,  : 
  unused argument (filter.high.mit.fraction = T)
```
Should `filter.high.mit.fraction` be `filter.mitochondrial`?
L75 & L76:
```
Error in EstimateCellsQuality(pipeline_data$aligned_umis_per_cell) : 
  could not find function "EstimateCellsQuality"
```
EstimateCellsQuality does not appear to be exported from dropestr namespace. E.g the following does work:
`cells_quality <- dropestr:::EstimateCellsQuality(pipeline_data$aligned_umis_per_cell)`
But this doesn't solve L76:
```
cells_quality_manual <- dropestr:::EstimateCellsQuality(pipeline_data$aligned_umis_per_cell, cells.number=cells_number_manual)
Error in dropestr:::EstimateCellsQuality(pipeline_data$aligned_umis_per_cell,  : 
  unused argument (cells.number = cells_number_manual)
```
L78 & L79:
```
Error in FilterMitochondrionCells(mit_geneset_fraction, cells_quality,  : 
  could not find function "FilterMitochondrionCells"
```

Both I and @TomSmithCGAT are stuck at this step along with one mentioned in https://github.com/hms-dbmi/dropEst/issues/51, any help is highly appreciated.

**Comment by lucacozzuto** [comment]
Dear all, I'm also stuck at this point... I would like to extract the good cells and the corresponding genes... can someone help on this?

**Comment by connersk** [comment]
I too am finding this vignette rather difficult to follow

**Comment by connersk** [comment]
If you directly download and source this file you can get EstimateCellsQuality https://github.com/hms-dbmi/dropEst/blob/master/dropestr/R/low_quality_cells.R.

But I can't seem to find  the FilterMitochondrionCells function anywhere and the ScorePipelineCells function returns the error "Error in if (any(abs(normalizer) < 1e-10)) { : missing value where TRUE/FALSE needed" when I try and run on data that I obtained from using the pipeline

**Comment by connersk** [comment]
I'm also having a similar problem when trying to use the UMI correction vignette. When I run umis_distribution <- GetUmisDistribution(reads_per_umi_per_cell$readsper_umi)

I get the error, Error in GetUmisDistributionOld(reads.per.umi.per.cb, smooth = smooth) : 
  could not find function "GetUmisDistributionOld"

From search in the github repository I can see that GetUmisDistributionOld is defined in dropEst/dropestr/src/utils.cpp

I know very little about how R packages work so I could definitely be wrong, but functions defined in the src folder are the problem?

**Comment by lucacozzuto** [comment]
Still no news on this really important part of the workflow?

**Comment by TomSmithCGAT** [comment]
As far as I can tell, the repository is maintained by a single PhD stduent. Speaking as someone who frequently takes weeks to respond to issues (not ideal I know), I can understand 8 days without a response. This appears to require a relatively minor debug so fingers crossed for a resolution soon.

**Comment by VPetukhov** [comment]
Hi guys,
Sorry for making you wait. @TomSmithCGAT you're exactly right, thank you for understanding.
I fixed the vignette in the last commit: 7651986.

**Comment by lucacozzuto** [comment]
Thanks a lot @VPetukhov and sorry for being so pushy but I really like this tool :) Thanks again!

**Comment by lucacozzuto** [comment]
Sorry... I still see a problem with this:
```
Error: could not find function "ScoreQualityData"
`
``

**Comment by connersk** [comment]
Agreed, awesome tool thanks @VPetukhov, appreciate it!

**Comment by connersk** [comment]
Thanks again for supporting this @VPetukhov. I think that there is a similar issue with the UMI correction vignette. When I run the GetUmisDistribution function, I get the error:

Error in GetUmisDistributionOld(reads.per.umi.per.cb, smooth = smooth) : 
  could not find function "GetUmisDistributionOld"

Which I believe indicates that the GetUMIsDistributionOld function isn't is not exported from the DropestR namespace.
